import { useEffect, useRef, useState } from "react";
import { useLang } from "@/lib/i18n";
import { gsap, MOTION_OK } from "@/lib/motion";
import { SectionHead } from "./ui";

export function Services() {
  const { t } = useLang(); const ref = useRef<HTMLElement>(null); const [active, setActive] = useState(0);
  useEffect(() => { const mm = gsap.matchMedia(); mm.add(MOTION_OK, () => { const root = ref.current; if (!root) return; const rows = gsap.utils.toArray<HTMLElement>(".receipt-line", root); rows.forEach((row, i) => gsap.fromTo(row,{clipPath:"inset(0 0 100% 0)"},{clipPath:"inset(0 0 0% 0)",ease:"none",scrollTrigger:{trigger:row,start:"top 85%",end:"top 58%",scrub:true,onEnter:()=>setActive(i),onEnterBack:()=>setActive(i)}})); gsap.fromTo(root.querySelector(".paid-stamp"),{opacity:0,rotate:-16,scale:.8},{opacity:1,rotate:-7,scale:1,duration:.55,ease:"power3.out",scrollTrigger:{trigger:".paid-stamp",start:"top 82%",once:true}}); }); return () => mm.revert(); }, []);
  return <section id="usluge" ref={ref} className="relative z-10 py-28 md:py-40"><div className="container-grid"><SectionHead label={t.services.label} right={t.services.title}/><div className="mt-12 grid grid-cols-12 gap-8 md:mt-20">
    <aside className="col-span-12 md:col-span-3"><div className="md:sticky md:top-28"><p className="text-2xl font-medium leading-tight">{t.services.receipt.note}</p><p className="mt-8 text-muted-foreground">{t.services.receipt.side[active]}</p></div></aside>
    <div className="receipt col-span-12 px-5 py-8 md:col-span-6 md:col-start-4 md:px-10"><div className="border-b border-dashed border-hairline pb-7 text-center"><div className="font-semibold">Radenon Digital</div><div className="mt-2 font-mono text-xs text-muted-foreground">{t.services.receipt.title}</div></div><ol className="py-4">{t.services.items.map((s,i)=><li key={s.t} className="receipt-line grid grid-cols-[auto_1fr_auto] gap-3 border-b border-dashed border-hairline py-5 font-mono text-xs"><span>{String(i+1).padStart(2,"0")}</span><span><strong className="font-medium">{s.t}</strong><small className="mt-1 block font-sans text-muted-foreground">{s.del[0]}</small></span><span className="self-start text-muted-foreground">{t.services.receipt.included}</span></li>)}</ol><div className="flex items-end justify-between border-t border-foreground pt-5 font-mono"><span>{t.services.receipt.total}</span><strong className="text-2xl">{t.packages.from} 199 €</strong></div><div className="paid-stamp mt-8 ml-auto w-fit border-2 border-primary px-4 py-2 font-mono text-xs font-semibold text-foreground">{t.services.receipt.paid}</div></div>
    <aside className="col-span-12 md:col-span-3"><div className="md:sticky md:top-28"><span className="font-mono text-xs text-muted-foreground">{String(active+1).padStart(2,"0")} / {String(t.services.items.length).padStart(2,"0")}</span><h3 className="mt-4 text-3xl font-medium">{t.services.items[active]?.t}</h3><p className="mt-4 text-muted-foreground">{t.services.items[active]?.d}</p></div></aside>
  </div></div></section>;
}