/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KonsultacijaRouteImport } from './routes/konsultacija'
import { Route as IndexRouteImport } from './routes/index'

const KonsultacijaRoute = KonsultacijaRouteImport.update({
  id: '/konsultacija',
  path: '/konsultacija',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/konsultacija': typeof KonsultacijaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/konsultacija': typeof KonsultacijaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/konsultacija': typeof KonsultacijaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/konsultacija'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/konsultacija'
  id: '__root__' | '/' | '/konsultacija'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KonsultacijaRoute: typeof KonsultacijaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/konsultacija': {
      id: '/konsultacija'
      path: '/konsultacija'
      fullPath: '/konsultacija'
      preLoaderRoute: typeof KonsultacijaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KonsultacijaRoute: KonsultacijaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
